import type { Metadata } from 'next'
import './globals.css'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import HeaderNav from '@/components/headerNav'
import ReactQueryClientProvider from './ReactQueryClientProvider'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { AppProvider } from './contexts/app.context'

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Baemin',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='h-fit w-full'>
        <ReactQueryClientProvider>
          <AppProvider>
            <HeaderNav />
            <AntdRegistry>{children}</AntdRegistry>
            <ToastContainer />
          </AppProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  )
}
